### ISSUE TITLE
 Proper Alert Missing

### ISSUE THREAD

**Issue by karmakarsrija** [indic-amigo-akademi/krishi-mitra#5]
### Description
Proper alert is missing in this use cases.

### Steps

1. Customer applies for seller role for more than once by clicking on "Sell On Krishi-Mitra" page
2. Customer applies for admin role for more than once by visiting the admin register page.
3. An admin visits the Admin Register page
4. A verified seller visits the Admin Register page
5. User clicks on the decrease quantity button "-" of a product whose current quantity is equal to 1.
6. click on delete for a specific address

### Expected

1. redirects to the home page and displays a message that "Waiting! Already signed for seller approval!"
2. redirects to the home page and displays a message that "Waiting! Already signed for admin approval!"
3. redirects the admin to the home page and displays a message that "You are already registered as an Admin"
4. redirects the seller to the home page and displays a message that "You are already registered as a Seller"
5. System displays an alert box containing a removal confirmation message with Yes and No buttons
6. system remove the address from database and confirmation message will come "address deleted"

### Outcomes

1. redirects to the Seller Register page without showing any proper alert 
2. redirects to the Admin Register page without showing any proper alert
3. redirects the admin to the Admin Register page without showing any message
4. redirects the seller to the Admin Register page without showing any message
5. System displays an alert box containing a removal confirmation message with only a Ok button and no No button  
6. no confirmation message is shown.

**Comment by shivishbrahma** [comment]
Created a new helper library Notifilix using notifilix js... Resolve all alert and toast related issues... Check commit 526eb7c
