### ISSUE TITLE
Admin Auth Register Credential Bug

### ISSUE THREAD

**Issue by karmakarsrija** [indic-amigo-akademi/krishi-mitra#6]
Description: Admin Auth use case

### Step

1. Customer applies for admin role with different credentials.

### Expected

1. redirects to the same admin register page and displaying a Invalid Credentials message.

### Outcomes

1. redirects to the same admin register page but does not display the Invalid Credentials message

**Comment by shivishbrahma** [comment]
Resolved this in issue fix of #5
