### ISSUE TITLE
Product Negative Value Bug

### ISSUE THREAD

**Issue by karmakarsrija** [indic-amigo-akademi/krishi-mitra#7]
Description: Product Negative Value Bug
### Steps

1. seller gives quantity :0.
2. seller gives quantity:-5.
3. seller gives price: -10.
4. seller gives discount:-1.6

### Expected

1. System rejects it.
2. System rejects it.
3. System rejects it.
4. System rejects it

### Outcomes

1. System accept it.
2. System accept it.
3. System accept it.
4. System accept it

**Comment by shivishbrahma** [comment]
Done it... Please check 75fc2eb

**Comment by shivishbrahma** [comment]
Have fixed the frontend issues and provided validation. Check 75fc2eb
