### ISSUE TITLE
Order History UI Issue

### ISSUE THREAD

**Issue by karmakarsrija** [indic-amigo-akademi/krishi-mitra#8]
Description: Order History UI Issue
### Steps

1. Verified user clicks on My Orders in the home page (with placed orders).
2. User clicks on the Order ID of a particular order.
3. Verified Seller clicks on the Seller Dashboard on the home page.
4. Seller clicks on the Order ID of a particular received order.
5. Customer clicks on the Order ID of a particular order from the list of orders in My Orders page

### Expected
1.System shows list of orders placed by the user containing the following fields for each order:-
 Order ID,  Total Price, Date, Time and Status of the Order,  Seller Name, Name, type and quantity of each item for each order.
2. Cancel order Button should be shown.
3. System shows two buttons:-Browse Products, Browse ordered products.
4. System shows the order details containing the following fields:-
List of Items, Name, type, quantity and seller name of each item, Price of each item Delivery Address and Customer details, Date, Time and Status of the Order .
5. Cancel order button should be shown.

### Outcomes

1. System shows list of orders placed by the user containing the following fields for each order:-
Order ID,  Total Price, Date, Time of the Order, Name of the Seller Name and quantity of each item for each order.
2. Cancel order Button is Missing. 
3. Browse Ordered Product is missing.
4. Status of the order is missing.
5. Cancel order button is missing.

**Comment by shivishbrahma** [comment]
These UI changes were minor but still done... Check 409e2b6 and d3c2c3a
